### PR TITLE
Make it possible to have a non-toggleable action enable switch

### PR DESCRIPTION
**Pull request by juyrjola**

### CODE REVIEW

**Comment by jtuomist** [comment]
@juyrjola  this approach has the problem that if is_visible: false, then value: true does not have an effect and the action is always not done. Whether the action is done or not must be editable at the yaml file.

**Review by woodwoerk — APPROVED** [review]
Nice improvements, those queries are looking much cleaner 😊 just some nitpicks/ questions. I wasn't able to test this locally, a brief description/ screenshot or test instructions would be really helpful in future.

**Comment by woodwoerk** [comment]
@juyrjola Do you plan on merging this? Is it still in development?

**Comment by juyrjola** [comment]
Closed as merged through a rebase.

**Pull request closed without merging**
